services:

  mssql:
    image: ${SITECORE_NONPRODUCTION_DOCKER_REGISTRY}nonproduction/mssql-developer:2017-${EXTERNAL_IMAGE_TAG_SUFFIX}

  mssql-init:
    image: ${SITECORE_DOCKER_REGISTRY}sitecore-xmcloud-mssql-init:${SITECORE_VERSION}

  solr:
    image: ${SITECORE_NONPRODUCTION_DOCKER_REGISTRY}nonproduction/solr:8.8.2-${EXTERNAL_IMAGE_TAG_SUFFIX}

  solr-init:
    image: ${SITECORE_DOCKER_REGISTRY}sitecore-xmcloud-solr-init:${SITECORE_VERSION}

  cm:
    image: ${REGISTRY}${COMPOSE_PROJECT_NAME}-xmcloud-cm:${VERSION:-latest}
    build:
      context: ./glitteraudit/docker/build/cm
      args:
        PARENT_IMAGE: ${SITECORE_DOCKER_REGISTRY}sitecore-xmcloud-cm:${SITECORE_VERSION}
        TOOLS_IMAGE: ${TOOLS_IMAGE}

  grafana:
    image: ${REGISTRY}${COMPOSE_PROJECT_NAME}-grafana:${VERSION:-latest}
    build:
      context: ./glitterbucket/grafana
      args:
        BASE_IMAGE: mcr.microsoft.com/windows/servercore:${EXTERNAL_IMAGE_TAG_SUFFIX}
    ports:
      - "3000:3000"
    volumes:
      - "./glitterbucket/data/grafana:c:/data"
    environment:
      GF_PATHS_DATA: c:\data

  elasticsearch:
    image: ${REGISTRY}${COMPOSE_PROJECT_NAME}-elasticsearch:${VERSION:-latest}
    build:
      context: ./glitterbucket/elasticsearch
    volumes:
      - "./glitterbucket/data/elasticsearch:c:/data"

  glitterbucket:
    image: ${REGISTRY}${COMPOSE_PROJECT_NAME}-glitterbucket:${VERSION:-latest}
    build:
      context: ./glitterbucket/site
